databases:
  - name: budget-2023
    databaseName: budget_2023
    user: budget_2023_user

services:
  - type: web
    name: BudgetBuddy
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget-2023
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false